/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/analysis/estimate': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Single (or pooled multi-year) estimate
     * @description Computes one survey-weighted estimate for the selected activity, population, and years, with an official replicate-weight standard error and confidence interval unless `variance` is `none`. Multi-year requests are pooled into one estimate (use the trend endpoint for per-year series). Estimates are weighted population statistics per ATUS User's Guide ch. 7 — never unweighted sample means.
     */
    post: operations['estimate_api_v1_analysis_estimate_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/analysis/trend': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Per-year trend
     * @description Computes one estimate per requested year. Years that cannot be validly estimated under the requested weight scheme (2020 under `multiyear`) are returned as explicit unavailable points with a reason — never silently dropped, and never serialized as zero.
     */
    post: operations['trend_api_v1_analysis_trend_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/analysis/compare': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Two-population comparison
     * @description Estimates the same measure for two populations (each group filter is merged onto the shared `population` filter) plus their difference (group_a − group_b). The difference's standard error is computed from per-replicate differences, which accounts for the covariance between the overlapping-sample group estimates.
     */
    post: operations['compare_api_v1_analysis_compare_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/activities': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List/search the activity lexicon
     * @description Flat listing of the harmonized 2003-25 activity coding lexicon (18 major categories, 107 subcategories, 431 leaf activities), filterable by level, direct parent, and name search. In analysis requests, a 2- or 4-digit code selects itself plus all descendants.
     */
    get: operations['list_activities_api_v1_activities_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/activities/presets': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Named activity selections
     * @description Curated selections usable as {'preset': name} in analysis requests, including the BLS news-release table category definitions (verified against published Table A-1 values).
     */
    get: operations['list_presets_api_v1_activities_presets_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/activities/{code}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** One lexicon code with its ancestry and children */
    get: operations['activity_detail_api_v1_activities__code__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/population/metadata': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Supported population filter dimensions
     * @description Every population dimension analysis requests may filter on, with valid values for categorical dimensions. Served from the analytical engine's own dimension registry, so this vocabulary cannot drift from what filtering actually accepts.
     */
    get: operations['population_metadata_api_v1_population_metadata_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/meta': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * API, analytics, and data versions plus capability discovery
     * @description What this service can compute and against which data. `api_version` is the HTTP contract; `analytics_version` is the statistical implementation (a change means computed numbers may differ); `data` identifies the loaded BLS release and ingestion run. Clients should discover capabilities here instead of hard-coding them.
     */
    get: operations['meta_api_v1_meta_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Liveness
     * @description Answers whether the API process is running. No dependencies touched. Async on purpose: it bypasses the worker threadpool, so liveness stays instant even when every worker thread is busy with long analyses.
     */
    get: operations['health_health_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/ready': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Readiness
     * @description Verifies the dependencies needed to answer analysis requests: the database is reachable and ATUS data is loaded. The (optional) result cache is not a readiness dependency — the service degrades gracefully without it. Readiness assumes the database passed `atus validate-db` at load time; it does not re-run data-quality checks.
     */
    get: operations['ready_ready_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** ActivityDetailResponse */
    ActivityDetailResponse: {
      /** Code */
      code: string
      /** Name */
      name: string
      /** Level */
      level: number
      /**
       * Parents
       * @description Ancestors, outermost first.
       */
      parents: components['schemas']['ActivityEntry'][]
      /**
       * Children
       * @description Direct children (empty for level 3).
       */
      children: components['schemas']['ActivityEntry'][]
      /** Harmonization Note */
      harmonization_note?: string | null
      /**
       * Descendant Leaf Count
       * @description Number of 6-digit codes selected when this code is used in an analysis (a tier code means itself plus all descendants).
       */
      descendant_leaf_count: number
    }
    /** ActivityEntry */
    ActivityEntry: {
      /**
       * Code
       * @description Harmonized 2003-25 lexicon code (2, 4, or 6 digits).
       */
      code: string
      /** Name */
      name: string
      /**
       * Level
       * @description 1 = major category, 2 = subcategory, 3 = 6-digit activity.
       */
      level: number
      /**
       * Parent Code
       * @description Immediate parent code (null for major categories).
       */
      parent_code?: string | null
      /**
       * Harmonization Note
       * @description BLS note on retired codes this harmonized code absorbs (level 3 only).
       */
      harmonization_note?: string | null
    }
    /** ActivityInfoModel */
    ActivityInfoModel: {
      /** Label */
      label: string
      /** Include */
      include: string[]
      /** Exclude */
      exclude: string[]
      /**
       * Leaf Code Count
       * @description Number of 6-digit codes the selection resolves to.
       */
      leaf_code_count: number
    }
    /**
     * ActivityListResponse
     * @example {
     *       "activities": [
     *         {
     *           "code": "01",
     *           "level": 1,
     *           "name": "Personal Care Activities"
     *         },
     *         {
     *           "code": "0101",
     *           "level": 2,
     *           "name": "Sleeping",
     *           "parent_code": "01"
     *         },
     *         {
     *           "code": "010101",
     *           "level": 3,
     *           "name": "Sleeping",
     *           "parent_code": "0101"
     *         }
     *       ],
     *       "total": 3
     *     }
     */
    ActivityListResponse: {
      /** Activities */
      activities: components['schemas']['ActivityEntry'][]
      /**
       * Total
       * @description Entries returned after filters (the lexicon is small).
       */
      total: number
    }
    /** ActivityPreset */
    ActivityPreset: {
      /**
       * Name
       * @description Value to use as {'preset': name} in analysis requests.
       */
      name: string
      /** Label */
      label: string
      /** Include */
      include: string[]
      /** Exclude */
      exclude: string[]
    }
    /** ActivityPresetsResponse */
    ActivityPresetsResponse: {
      /** Presets */
      presets: components['schemas']['ActivityPreset'][]
    }
    /**
     * ActivitySelection
     * @description Which activities to measure: a named preset, or explicit lexicon codes.
     *
     *     A 2- or 4-digit code selects that tier and all of its descendants; an
     *     episode matches when its 6-digit code falls under any `include` entry and
     *     under no `exclude` entry. Codes are validated against the loaded lexicon.
     */
    ActivitySelection: {
      /**
       * Preset
       * @description Named selection (see GET /api/v1/activities/presets).
       */
      preset?: string | null
      /**
       * Include
       * @description Codes/tier prefixes to include.
       */
      include?: string[] | null
      /**
       * Exclude
       * @description Codes/tier prefixes to exclude.
       */
      exclude?: string[]
      /** Label */
      label?: string | null
    }
    /** CapabilitiesInfo */
    CapabilitiesInfo: {
      /** Measures */
      measures: components['schemas']['MeasureInfo'][]
      /** Weight Schemes */
      weight_schemes: components['schemas']['WeightSchemeInfo'][]
      /** Variance Methods */
      variance_methods: string[]
      /** Confidence Level Default */
      confidence_level_default: number
      /** Activity Presets */
      activity_presets: string[]
      /** Population Dimensions */
      population_dimensions: string[]
      /**
       * Limits
       * @description Request limits (max years, max activity codes, ...).
       */
      limits: {
        [key: string]: unknown
      }
      /**
       * Unsupported
       * @description Explicitly out-of-scope analysis types (do not infer support).
       */
      unsupported: string[]
    }
    /**
     * CompareRequest
     * @description Two populations, one measure. Group filters are merged onto the shared
     *     `population` filter; the difference's standard error is computed from
     *     per-replicate differences (covariance-correct).
     * @example {
     *       "activity": {
     *         "preset": "household_activities_bls_table"
     *       },
     *       "group_a": {
     *         "sex": "male"
     *       },
     *       "group_b": {
     *         "sex": "female"
     *       },
     *       "label_a": "Men",
     *       "label_b": "Women",
     *       "measure": "average_minutes_per_day",
     *       "years": [
     *         2025
     *       ]
     *     }
     */
    CompareRequest: {
      /**
       * Measure
       * @description ATUS User's Guide ch. 7.4 estimator (see GET /api/v1/meta).
       * @default average_minutes_per_day
       * @enum {string}
       */
      measure?:
        | 'average_minutes_per_day'
        | 'participation_rate'
        | 'average_minutes_per_participant'
        | 'participants_per_day'
      activity: components['schemas']['ActivitySelection']
      /**
       * Years
       * @description Survey years. Order-insensitive; duplicates are rejected.
       */
      years: number[]
      population?: components['schemas']['PopulationRequest']
      /**
       * Weights
       * @description Weight scheme: 'multiyear' (TUFNWGTP; refuses 2020) or 'pandemic' (TU20FWGT; 2019/2020 only).
       * @default multiyear
       * @enum {string}
       */
      weights?: 'multiyear' | 'pandemic'
      /**
       * Variance
       * @description 'replicate' = official 160-replicate-weight standard errors; 'none' = point estimate only (faster).
       * @default replicate
       * @enum {string}
       */
      variance?: 'replicate' | 'none'
      /**
       * Confidence Level
       * @default 0.95
       */
      confidence_level?: number
      group_a: components['schemas']['PopulationRequest']
      group_b: components['schemas']['PopulationRequest']
      /**
       * Label A
       * @default group_a
       */
      label_a?: string
      /**
       * Label B
       * @default group_b
       */
      label_b?: string
    }
    /** CompareResponse */
    CompareResponse: {
      /** Measure */
      measure: string
      /** Label A */
      label_a: string
      /** Label B */
      label_b: string
      group_a: components['schemas']['EstimateResponse']
      group_b: components['schemas']['EstimateResponse']
      /** @description group_a − group_b; SE from per-replicate differences (covariance-correct). */
      difference: components['schemas']['EstimateValueModel']
      /** Analytics Version */
      analytics_version: string
      /** Warnings */
      warnings: string[]
    }
    /** DataInfo */
    DataInfo: {
      /**
       * Release
       * @description BLS multi-year release code, e.g. '0325' = 2003-2025.
       */
      release: string
      /**
       * Years
       * @description Survey years loaded and queryable.
       */
      years: number[]
      /**
       * Respondents
       * @description Unweighted respondent count in the database.
       */
      respondents: number
      /**
       * Last Ingested At
       * @description Timestamp of the last successful ingestion run (ISO-8601).
       */
      last_ingested_at?: string | null
      /**
       * Ingestion Run Id
       * @description Identifier of the last successful ingestion run.
       */
      ingestion_run_id?: number | null
    }
    /** ErrorDetail */
    ErrorDetail: {
      /**
       * Code
       * @description Stable machine-readable error code, e.g. 'unsupported_analysis'.
       */
      code: string
      /**
       * Message
       * @description Human-readable explanation.
       */
      message: string
      /**
       * Details
       * @description Optional structured context (never stack traces).
       */
      details?: {
        [key: string]: unknown
      } | null
    }
    /**
     * ErrorResponse
     * @example {
     *       "error": {
     *         "code": "unsupported_analysis",
     *         "message": "TUFNWGTP (the multi-year weight) is undefined for 2020 because ATUS data collection was suspended Mar 18 - May 9, 2020 and the year was reweighted with a different method (TU20FWGT). A single estimate pooling 2020 with this scheme is not statistically valid. Estimate 2020 separately with weights='pandemic' (years may only be 2019 and/or 2020 under that scheme)."
     *       }
     *     }
     */
    ErrorResponse: {
      error: components['schemas']['ErrorDetail']
    }
    /**
     * EstimateRequest
     * @description One estimate for the whole requested period (pooled if several years).
     * @example {
     *       "activity": {
     *         "preset": "sleep"
     *       },
     *       "measure": "average_minutes_per_day",
     *       "years": [
     *         2025
     *       ]
     *     }
     * @example {
     *       "activity": {
     *         "include": [
     *           "120303",
     *           "120304"
     *         ],
     *         "label": "Watching TV"
     *       },
     *       "measure": "participation_rate",
     *       "variance": "replicate",
     *       "years": [
     *         2024
     *       ]
     *     }
     * @example {
     *       "activity": {
     *         "preset": "sleep"
     *       },
     *       "measure": "average_minutes_per_day",
     *       "population": {
     *         "diary_date_min": "2020-05-10"
     *       },
     *       "weights": "pandemic",
     *       "years": [
     *         2020
     *       ]
     *     }
     */
    EstimateRequest: {
      /**
       * Measure
       * @description ATUS User's Guide ch. 7.4 estimator (see GET /api/v1/meta).
       * @default average_minutes_per_day
       * @enum {string}
       */
      measure?:
        | 'average_minutes_per_day'
        | 'participation_rate'
        | 'average_minutes_per_participant'
        | 'participants_per_day'
      activity: components['schemas']['ActivitySelection']
      /**
       * Years
       * @description Survey years. Order-insensitive; duplicates are rejected.
       */
      years: number[]
      population?: components['schemas']['PopulationRequest']
      /**
       * Weights
       * @description Weight scheme: 'multiyear' (TUFNWGTP; refuses 2020) or 'pandemic' (TU20FWGT; 2019/2020 only).
       * @default multiyear
       * @enum {string}
       */
      weights?: 'multiyear' | 'pandemic'
      /**
       * Variance
       * @description 'replicate' = official 160-replicate-weight standard errors; 'none' = point estimate only (faster).
       * @default replicate
       * @enum {string}
       */
      variance?: 'replicate' | 'none'
      /**
       * Confidence Level
       * @default 0.95
       */
      confidence_level?: number
    }
    /**
     * EstimateResponse
     * @example {
     *       "activity": {
     *         "exclude": [],
     *         "include": [
     *           "0101"
     *         ],
     *         "label": "Sleeping",
     *         "leaf_code_count": 3
     *       },
     *       "analytics_version": "0.2",
     *       "days_in_period": 365,
     *       "estimate": {
     *         "ci_lower": 537.7184958624899,
     *         "ci_upper": 546.2099048966699,
     *         "confidence_level": 0.95,
     *         "standard_error": 2.166215578745084,
     *         "unit": "minutes_per_day",
     *         "value": 541.9642003795799
     *       },
     *       "measure": "average_minutes_per_day",
     *       "n_participants": 6139,
     *       "n_respondents": 6146,
     *       "population": "civilian noninstitutional population age 15+",
     *       "spec": {
     *         "activity": {
     *           "exclude": [],
     *           "include": [
     *             "0101"
     *           ],
     *           "label": "Sleeping"
     *         },
     *         "confidence_level": 0.95,
     *         "measure": "average_minutes_per_day",
     *         "population": {},
     *         "variance": "replicate",
     *         "weights": "multiyear",
     *         "years": [
     *           2025
     *         ]
     *       },
     *       "variance_method": "replicate",
     *       "warnings": [
     *         "Activity codes use the BLS-harmonized 2003-25 multi-year lexicon (cross-year comparable by construction)."
     *       ],
     *       "weight": {
     *         "bls_variable": "TUFNWGTP",
     *         "column": "respondents.final_weight",
     *         "scheme": "multiyear"
     *       },
     *       "weighted_population_per_day": 277984657.483597,
     *       "years": [
     *         2025
     *       ]
     *     }
     */
    EstimateResponse: {
      /** Measure */
      measure: string
      estimate: components['schemas']['EstimateValueModel']
      /** Years */
      years: number[]
      activity: components['schemas']['ActivityInfoModel']
      /**
       * Population
       * @description Human-readable population definition.
       */
      population: string
      /**
       * N Respondents
       * @description UNWEIGHTED sample size (respondents).
       */
      n_respondents: number
      /**
       * N Participants
       * @description UNWEIGHTED respondents with any time in the activity.
       */
      n_participants: number
      /**
       * Weighted Population Per Day
       * @description Persons represented on an average day of the period (Σweights / days).
       */
      weighted_population_per_day: number
      /** Days In Period */
      days_in_period: number
      weight: components['schemas']['WeightInfoModel']
      /** Variance Method */
      variance_method: string
      /** Analytics Version */
      analytics_version: string
      /**
       * Spec
       * @description The exact canonical analysis specification — resubmit it to reproduce this result.
       */
      spec: {
        [key: string]: unknown
      }
      /**
       * Warnings
       * @description Methodological notes a client should display, never discard.
       */
      warnings: string[]
    }
    /** EstimateValueModel */
    EstimateValueModel: {
      /**
       * Value
       * @description The estimate, in `unit`.
       */
      value: number
      /**
       * Unit
       * @description minutes_per_day | proportion_of_population (0-1) | minutes_per_day_of_participants | persons_per_day
       */
      unit: string
      /**
       * Standard Error
       * @description Replicate-weight SE (User's Guide ch. 7.5); null when variance='none'.
       */
      standard_error?: number | null
      /** Confidence Level */
      confidence_level?: number | null
      /** Ci Lower */
      ci_lower?: number | null
      /** Ci Upper */
      ci_upper?: number | null
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][]
    }
    /** MeasureInfo */
    MeasureInfo: {
      /** Name */
      name: string
      /** Unit */
      unit: string
      /** Description */
      description: string
    }
    /** MetaResponse */
    MetaResponse: {
      /**
       * Api Version
       * @description HTTP contract version (path prefix /api/v1).
       */
      api_version: string
      /**
       * Analytics Version
       * @description Statistical implementation version — a change means computed results may differ.
       */
      analytics_version: string
      data: components['schemas']['DataInfo']
      capabilities: components['schemas']['CapabilitiesInfo']
    }
    /** PopulationDimension */
    PopulationDimension: {
      /**
       * Name
       * @description Field name to use inside analysis 'population' objects.
       */
      name: string
      /**
       * Type
       * @description integer | category | boolean | date
       */
      type: string
      /** Description */
      description: string
      /**
       * Values
       * @description Valid values for categorical dimensions.
       */
      values?: unknown[] | null
      /** Unit */
      unit?: string | null
      /** Notes */
      notes?: string | null
    }
    /** PopulationMetadataResponse */
    PopulationMetadataResponse: {
      /** Dimensions */
      dimensions: components['schemas']['PopulationDimension'][]
      /**
       * Missing Data Rule
       * @description How missing values interact with filters (applies to every dimension).
       */
      missing_data_rule: string
      /**
       * Default Universe
       * @description The population when no filters are set.
       */
      default_universe: string
    }
    /**
     * PopulationRequest
     * @description Respondent-level population restriction (all dimensions optional).
     *
     *     Filtering on a dimension excludes respondents whose value is missing for
     *     it — missing is never treated as "no". See GET /api/v1/population/metadata
     *     for dimension semantics and valid values.
     */
    PopulationRequest: {
      /** Age Min */
      age_min?: number | null
      /** Age Max */
      age_max?: number | null
      /** Sex */
      sex?: ('male' | 'female') | null
      /** Employment Status */
      employment_status?: ('employed' | 'unemployed' | 'not_in_labor_force') | null
      /** Has Household Children */
      has_household_children?: boolean | null
      /**
       * Region
       * @description Census region: 1 NE, 2 MW, 3 South, 4 West
       */
      region?: number | null
      /** State Fips */
      state_fips?: string | null
      /** Education Level */
      education_level?:
        | (
            | 'less_than_high_school'
            | 'high_school'
            | 'some_college_or_associate'
            | 'bachelor_or_higher'
          )
        | null
      /** Day Type */
      day_type?: ('weekday' | 'weekend') | null
      /** Diary Date Min */
      diary_date_min?: string | null
      /** Diary Date Max */
      diary_date_max?: string | null
    }
    /** TrendPointModel */
    TrendPointModel: {
      /** Year */
      year: number
      /** @description null when the year cannot be validly estimated — see unavailable_reason. Never serialized as zero. */
      estimate?: components['schemas']['EstimateValueModel'] | null
      /** N Respondents */
      n_respondents?: number | null
      /** N Participants */
      n_participants?: number | null
      /** Weighted Population Per Day */
      weighted_population_per_day?: number | null
      /** Unavailable Reason */
      unavailable_reason?: string | null
    }
    /**
     * TrendRequest
     * @description Per-year estimates. Years that cannot be validly estimated (e.g. 2020
     *     under the multiyear weights) come back as explicit unavailable points.
     * @example {
     *       "activity": {
     *         "preset": "leisure_and_sports_bls_table"
     *       },
     *       "measure": "average_minutes_per_day",
     *       "years": [
     *         2003,
     *         2004,
     *         2005,
     *         2006,
     *         2007,
     *         2008,
     *         2009,
     *         2010,
     *         2011,
     *         2012,
     *         2013,
     *         2014,
     *         2015,
     *         2016,
     *         2017,
     *         2018,
     *         2019,
     *         2020,
     *         2021,
     *         2022,
     *         2023,
     *         2024,
     *         2025
     *       ]
     *     }
     */
    TrendRequest: {
      /**
       * Measure
       * @description ATUS User's Guide ch. 7.4 estimator (see GET /api/v1/meta).
       * @default average_minutes_per_day
       * @enum {string}
       */
      measure?:
        | 'average_minutes_per_day'
        | 'participation_rate'
        | 'average_minutes_per_participant'
        | 'participants_per_day'
      activity: components['schemas']['ActivitySelection']
      /**
       * Years
       * @description Survey years. Order-insensitive; duplicates are rejected.
       */
      years: number[]
      population?: components['schemas']['PopulationRequest']
      /**
       * Weights
       * @description Weight scheme: 'multiyear' (TUFNWGTP; refuses 2020) or 'pandemic' (TU20FWGT; 2019/2020 only).
       * @default multiyear
       * @enum {string}
       */
      weights?: 'multiyear' | 'pandemic'
      /**
       * Variance
       * @description 'replicate' = official 160-replicate-weight standard errors; 'none' = point estimate only (faster).
       * @default replicate
       * @enum {string}
       */
      variance?: 'replicate' | 'none'
      /**
       * Confidence Level
       * @default 0.95
       */
      confidence_level?: number
    }
    /** TrendResponse */
    TrendResponse: {
      /** Measure */
      measure: string
      /** Points */
      points: components['schemas']['TrendPointModel'][]
      activity: components['schemas']['ActivityInfoModel']
      /** Population */
      population: string
      weight: components['schemas']['WeightInfoModel']
      /** Variance Method */
      variance_method: string
      /** Analytics Version */
      analytics_version: string
      /** Spec */
      spec: {
        [key: string]: unknown
      }
      /** Warnings */
      warnings: string[]
    }
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
      /** Input */
      input?: unknown
      /** Context */
      ctx?: Record<string, never>
    }
    /** WeightInfoModel */
    WeightInfoModel: {
      /** Scheme */
      scheme: string
      /**
       * Bls Variable
       * @description TUFNWGTP or TU20FWGT
       */
      bls_variable: string
      /** Column */
      column: string
    }
    /** WeightSchemeInfo */
    WeightSchemeInfo: {
      /** Name */
      name: string
      /** Bls Variable */
      bls_variable: string
      /** Valid Years */
      valid_years: string
      /** Description */
      description: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  estimate_api_v1_analysis_estimate_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['EstimateRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['EstimateResponse']
        }
      }
      /** @description Malformed JSON body */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Schema violation, or analytically invalid/unsupported request (e.g. 2020 under the multiyear weight scheme) */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Analytical database unavailable */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  trend_api_v1_analysis_trend_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['TrendRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TrendResponse']
        }
      }
      /** @description Malformed JSON body */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Schema violation, or analytically invalid/unsupported request (e.g. 2020 under the multiyear weight scheme) */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Analytical database unavailable */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  compare_api_v1_analysis_compare_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CompareRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CompareResponse']
        }
      }
      /** @description Malformed JSON body */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Schema violation, or analytically invalid/unsupported request (e.g. 2020 under the multiyear weight scheme) */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Analytical database unavailable */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  list_activities_api_v1_activities_get: {
    parameters: {
      query?: {
        level?: number | null
        /** @description Return direct children of this 2- or 4-digit code. */
        parent?: string | null
        search?: string | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ActivityListResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_presets_api_v1_activities_presets_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ActivityPresetsResponse']
        }
      }
    }
  }
  activity_detail_api_v1_activities__code__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        code: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ActivityDetailResponse']
        }
      }
      /** @description Unknown activity code */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  population_metadata_api_v1_population_metadata_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PopulationMetadataResponse']
        }
      }
    }
  }
  meta_api_v1_meta_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MetaResponse']
        }
      }
    }
  }
  health_health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            [key: string]: unknown
          }
        }
      }
    }
  }
  ready_ready_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Not ready */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
}
